import React from 'react';
import { Sparkles, ArrowRight, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

export function DailyBriefingCard({ briefing }) {
  if (!briefing) return null;

  return (
    <div className="relative overflow-hidden rounded-3xl p-6 md:p-8 bg-gradient-to-br from-indigo-900/90 via-slate-900 to-slate-950 border border-indigo-500/30 text-white shadow-2xl">
      {/* Soft Glowing Ambient Background Blur */}
      <div className="absolute -top-24 -right-24 w-72 h-72 bg-indigo-500/20 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-24 -left-24 w-72 h-72 bg-purple-500/20 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10 space-y-4">
        <div className="flex items-center justify-between">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-indigo-500/20 border border-indigo-400/30 text-indigo-300 text-xs font-semibold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5 text-indigo-400 animate-pulse" />
            <span>AI Daily Inbox Briefing</span>
          </div>
          <div className="flex items-center text-xs text-slate-400">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 mr-1" />
            <span>Inbox Health {briefing.inboxHealthScore}%</span>
          </div>
        </div>

        <div>
          <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight bg-gradient-to-r from-white via-indigo-100 to-indigo-200 bg-clip-text text-transparent">
            {briefing.greeting}
          </h2>
          <p className="text-sm md:text-base text-indigo-200/80 mt-1 font-medium">{briefing.headline}</p>
        </div>

        <p className="text-sm text-slate-300 leading-relaxed max-w-3xl">{briefing.summary}</p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
          {briefing.highlights.map((item, idx) => (
            <div key={idx} className="flex items-start space-x-2.5 p-3 rounded-xl bg-white/5 border border-white/10 text-xs text-slate-200">
              <span className="leading-snug">{item}</span>
            </div>
          ))}
        </div>

        <div className="pt-2 flex items-center justify-between border-t border-white/10">
          <span className="text-xs text-slate-400">Generated by Gemini 1.5 Flash • No emails sent automatically</span>
          <Link
            to="/inbox"
            className="inline-flex items-center space-x-1 text-xs font-semibold text-indigo-300 hover:text-white transition-colors"
          >
            <span>Review Urgent Inbox</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>
    </div>
  );
}
