const { getGeminiClient } = require('../config/gemini');
const { sanitizeFilename } = require('../utils/fileUtils');
const logger = require('../utils/logger');

/**
 * Analyze a document using Gemini AI to infer category, suggested filename, summary, confidence, and reason.
 */
const analyzeDocument = async (filename, extension, extractedText) => {
  const apiKey = process.env.GEMINI_API_KEY;

  // Fallback heuristic analyzer if no Gemini API Key is configured
  if (!apiKey || apiKey === 'your_gemini_api_key_here') {
    logger.warn(`No Gemini API key provided. Using intelligent rule-based heuristic fallback for ${filename}.`);
    return generateFallbackAnalysis(filename, extension, extractedText);
  }

  try {
    const ai = getGeminiClient();

    const systemInstruction = `
You are an expert AI File Organization Assistant. Analyze the provided document text, filename, and extension.

Rules:
1. "category": Generate the single most appropriate concise category name for this file (e.g., Personal, Finance, College, Research, Programming, Health, Work, Legal). Do NOT restrict yourself to a fixed list if a more accurate category fits better.
2. "suggestedName": Suggest a clean, descriptive, concise filename (max 60 characters). Preserve the exact original extension (${extension}). Do not use illegal characters (/ \\ : * ? " < > |).
3. "summary": Provide a concise 1-sentence summary of the document's core content.
4. "confidence": Integer percentage between 0 and 100 based on document clarity.
5. "reason": Provide exactly one sentence explaining why this filename and category were selected.

Return ONLY valid JSON matching this schema:
{
  "category": "string",
  "suggestedName": "string",
  "summary": "string",
  "confidence": 85,
  "reason": "string"
}
`;

    const model = ai.getGenerativeModel({
      model: 'gemini-1.5-flash',
      systemInstruction,
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.2
      }
    });

    const prompt = `
Filename: ${filename}
Extension: ${extension}

Extracted Document Content:
${extractedText.substring(0, 3000)}
`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    const parsed = JSON.parse(responseText);

    return {
      category: parsed.category || 'Uncategorized',
      suggestedName: sanitizeFilename(parsed.suggestedName || filename, extension),
      summary: parsed.summary || 'Summary generated by Gemini AI.',
      confidence: typeof parsed.confidence === 'number' ? Math.min(100, Math.max(0, parsed.confidence)) : 80,
      reason: parsed.reason || 'Categorized based on document content analysis.'
    };

  } catch (error) {
    logger.error(`Gemini API Error for file ${filename}: ${error.message}`);
    return generateFallbackAnalysis(filename, extension, extractedText);
  }
};

/**
 * Compare two document snippets using Gemini to determine if they represent the same content/document (Layer 2)
 */
const compareDocumentsForDuplicate = async (docA, docB) => {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || apiKey === 'your_gemini_api_key_here') {
    return { status: 'Unique', reason: 'Unique checksum (Gemini API key not configured for Layer 2)' };
  }

  try {
    const ai = getGeminiClient();
    const model = ai.getGenerativeModel({
      model: 'gemini-1.5-flash',
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.1
      }
    });

    const prompt = `
Compare Document A and Document B. Determine if they represent the same document, duplicate content, or different documents.

Document A (${docA.name}):
${(docA.text || '').substring(0, 1500)}

Document B (${docB.name}):
${(docB.text || '').substring(0, 1500)}

Return ONLY JSON:
{
  "status": "Duplicate" | "Possibly Duplicate" | "Unique",
  "reason": "One sentence explaining comparison"
}
`;

    const result = await model.generateContent(prompt);
    const parsed = JSON.parse(result.response.text());

    return {
      status: parsed.status || 'Unique',
      reason: parsed.reason || 'Evaluated via Gemini content comparison.'
    };
  } catch (error) {
    logger.warn(`Gemini Duplicate Comparison error: ${error.message}`);
    return { status: 'Unique', reason: 'Unique content structure.' };
  }
};

/**
 * Intelligent Fallback Heuristic Generator for offline / missing API key environments
 */
const generateFallbackAnalysis = (filename, extension, text) => {
  const lowerName = filename.toLowerCase();
  const lowerText = text.toLowerCase();

  let category = 'Documents';
  let reason = 'Categorized using filename heuristics.';

  if (lowerName.includes('resume') || lowerName.includes('cv') || lowerText.includes('education') || lowerText.includes('experience')) {
    category = 'Personal';
    reason = 'Identified as a resume or CV document.';
  } else if (lowerName.includes('invoice') || lowerName.includes('bill') || lowerName.includes('receipt') || lowerText.includes('total') || lowerText.includes('payment')) {
    category = 'Finance';
    reason = 'Identified as a financial invoice or receipt.';
  } else if (lowerName.includes('notes') || lowerName.includes('lecture') || lowerText.includes('assignment') || lowerText.includes('chapter')) {
    category = 'College';
    reason = 'Identified as academic lecture notes or coursework.';
  } else if (lowerName.includes('code') || lowerName.includes('script') || ['.js', '.py', '.java', '.cpp', '.html'].includes(extension)) {
    category = 'Programming';
    reason = 'Identified as source code or programming documentation.';
  } else if (lowerName.includes('health') || lowerName.includes('medical') || lowerName.includes('report') || lowerText.includes('patient') || lowerText.includes('doctor')) {
    category = 'Health';
    reason = 'Identified as medical or health report document.';
  }

  const cleanBase = filename.replace(extension, '').replace(/[-_]/g, ' ');
  const formattedName = cleanBase.charAt(0).toUpperCase() + cleanBase.slice(1);
  const suggestedName = sanitizeFilename(formattedName, extension);

  return {
    category,
    suggestedName,
    summary: text.length > 20 ? text.substring(0, 100).trim() + '...' : `File named ${filename}.`,
    confidence: 75,
    reason
  };
};

module.exports = {
  analyzeDocument,
  compareDocumentsForDuplicate
};
